Pet.destroy_all
Owner.destroy_all
Rescue.destroy_all

puts '🌱Seeding Owners'

o1 = Owner.create(name:"Lindsey", location: "NYC", phone_number: "111-111-1111")
o2 = Owner.create(name:"Kimberly", location: "NC", phone_number: "111-111-1111")

puts "🌱Seeding Rescues"
r1 = Rescue.create(name: "Brooklyn Animal Action", location: "NYC", phone_number: "222-222-2222")
r2 = Rescue.create(name: "Vets Unite", location: "California", phone_number: "222-222-2222")



puts "🌱 Seeding pets..."

p1 = Pet.create(name: "Bonnie", 
    species: "dog",
    breed: "Border Collie",
    age: "adult",
    gender: "girl",
    size: "small",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "null",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Bonnie is a 3 year old",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895007/1/?bust=1646687215&width=300",
    adoptable: "yes",
    url: "https://www.petfinder.com/dog/bonnie-54895007/nj/woodbury/good-karma-dog-rescue-nj890/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p2 = Pet.create(
    name: "Xena", 
    species: "dog",
    breed: "Rottweiler",
    age: "adult",
    gender: "girl",
    size: "large",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "XENA, girl ROTTWEILER, 65-70 POUNDS, 3.5 YEARS OLD",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895006/1/?bust=1646687213&width=300",
   adoptable: "yes",
    url: "https://www.petfinder.com/dog/xena-54895006/va/glen-allen/moms-va-va700/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o2.id
    )
p3 = Pet.create(
    name: "Yayo",
    species: "dog",
    breed: "Pit Bull terrier",
    age: "young",
    gender: "boy",
    size: "medium",
    spayed_neutered: "yes",
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "low",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "Yayo is a handsome guy with a big personality",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54804067/1/?bust=1646524989&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/dog/yayo-54804067/nc/fayetteville/cumberland-county-animal-services-nc448/",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p4 = Pet.create(
    name: "Lilly",
    species: "dog",
    breed: "maltipoo",
    age: "adult",
    gender: "girl" ,
    size: "small" ,
    spayed_neutered: "yes",
    housetrained: "yes", 
    hypoallergenic: "yes",
    activity_level: "High",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "Lilly is a 7.5 year old maltese/poodle mix. She is very friendly and sweet.",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54894990/1/?bust=1646687188&width=300",
    adoptable: "yes",
   url: "https://www.petfinder.com/dog/lilly-54894990/az/bisbee/bisbee-animal-shelter-az146/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
   rescue_id: r2.id,
   owner_id: o2.id
    )
p5 = Pet.create(
    name: "Petal",
    species: "dog",
    breed: "pug",
    age: "baby",
    gender:"girl",
    size: "small",
    spayed_neutered: "no",
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "Baby pug wants some love",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899214/1/?bust=1646746229&width=300",
   adoptable: "yes",
    url: "https://www.petfinder.com/dog/petal-54899214/md/ellicott-city/almost-home-dog-rescue-md482/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p6 = Pet.create(
    name: "August",
    species: "dog",
    breed: "labrador retriever",
    age: "young",
    gender: "boy", 
    size: "medium", 
    spayed_neutered: "yes",
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "Beautiful and energy young dog needs a home!" ,
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899215/1/?bust=1646746835&width=1080",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/august-54899215/tx/fort-davis/grand-companions-humane-society-tx570/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r2.id,
    owner_id: o2.id
    )
p7 = Pet.create(
    name: "Ace",
    species: "dog",
    breed: "beagle",
    age: "adult" ,
    gender: "boy",
    size: "medium", 
    spayed_neutered: "yes", 
    housetrained: "yes", 
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "Ace needs a compnion and best friend!", 
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899211/1/?bust=1646746213&width=300",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/ace-54899211/il/gilberts/project-hope-animal-rescue-il976/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p8 = Pet.create(
    name: "Rizzo",
    species: "dog" ,
    breed: "beagle",
    age: "adult", 
    gender: "boy",
    size: "medium" ,
    spayed_neutered: "yes", 
    housetrained: "yes", 
    hypoallergenic: "no",
    activity_level: "low",
    good_with_kids: "yes",
    good_with_animals: "yes", 
    description: "Rizzo needs a friend and he'll be a good boi he promises",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899208/1/?bust=1646746092&width=300",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/rizzo-54899208/il/gilberts/project-hope-animal-rescue-il976/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p9 = Pet.create(
    name: "Junior", 
    species: "dog",
    breed: "Boston Terrier",
    age: "senior",
    gender: "boy" ,
    size: "small", 
    spayed_neutered: "yes", 
    housetrained: "yes", 
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Junior is a friendly and old grumpy man",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899207/1/?bust=1646746074&width=300",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/junior-54899207/ri/foster/vintage-pet-rescue-ri144/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p11 = Pet.create(
    name: "Boba Fett",
    species: "dog",
    breed: "mixed breed", 
    age: "senior" ,
    gender: 'boy',
    size: "large",
    spayed_neutered: "yes", 
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no", 
    good_with_animals: "no",
    description: "Looking for the right man for you? Boba is perfeclty sweet and loving.",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899204/1/?bust=1646746030&width=300",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/boba-fett-54899204/oh/batavia/clermont-county-animal-shelter-oh1293/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p12 = Pet.create(
    name: "Blu",
    species: "dog",
    breed: "Australian Cattle Dog/ Blue Heeler",
    age: "adult",
    gender: "boy", 
    size: "medium", 
    spayed_neutered: "yes", 
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "no",
    good_with_animals: "yes", 
    description: "Muddy takes after his namespake and loves to roll around in it",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53373209/3/?bust=1645050341&width=1080",
    adoptable: "yes", 
    url: "https://www.petfinder.com/dog/blu-53373209/nc/raleigh/love-mutts-rescue-inc-nc716/",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p14 = Pet.create(
    name: "Heville" ,
    species: "dog", 
    breed: "Labrador retriever", 
    age: "baby" ,
    gender: "girl", 
    size: "medium", 
    spayed_neutered: "yes", 
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes",
    good_with_animals: "yes", 
    description: "Heville is a little demon dog, but in the best way possible. Lots of energy and lots of love" ,
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899197/1/?bust=1646745956&width=300",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/heville-54899197/ny/brewster/rosys-rescue-ny1555/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p15 =  Pet.create(
    name: "Sarge",
    species: "dog" ,
    breed: "German Shepherd",
    age: "adult" ,
    gender: "boy",
    size: "large",
    spayed_neutered: "yes",
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "You know what they say... An Army of One - that's me Sarge!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899196/3/?bust=1646746474&width=1080",
   adoptable: "yes",
    url: "https://www.petfinder.com/dog/sarge-army-of-one-49468-54899196/tx/pampa/pampa-animal-welfare-society-tx1492/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o1.id
    )
p16 = Pet.create(
    name:  "Jabba the Mutt",
    species: "dog" ,
    breed: "mixed breed" ,
    age: "adult",
    gender: "boy",
    size: "large" ,
    spayed_neutered: "yes", 
    housetrained: "no",  
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes", 
    good_with_animals: "no", 
    description: "Bring me treats and a human!", 
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899184/1/?bust=1646745834&width=300",
    adoptable: "yes",
    url: "https://www.petfinder.com/dog/jabba-the-mutt-54899184/oh/batavia/clermont-county-animal-shelter-oh1293/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r2.id,
    owner_id: o1.id
    ),
p17 = Pet.create(
    name: "Lulu", 
    species: "dog",
    breed: "Labrador Retreiver / Beagle",
    age: "adult",
    gender: "girl",
    size: "medium", 
    spayed_neutered: "yes", 
    housetrained: "yes", 
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes", 
    good_with_animals: "yes", 
    description: "Calm, Loving, Snuggle Bug",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899185/1/?bust=1646746439&width=1080",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/lulu-54899185/mn/mankato/mending-spirits-animal-rescue-mn379/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p18 = Pet.create(
    name:"Cache",
    species: "dog", 
    breed: "Labrador Retriever",
    age: "young",
    gender: "young",
    size: "large",
    spayed_neutered: "yes", 
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Cache is an active lab who is looking for a person or family to take him on all the adventures...",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54899201/1/?bust=1646746571&width=1080",
   adoptable: "yes", 
    url: "https://www.petfinder.com/dog/cache-54899201/ut/logan/cache-humane-society-ut45/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    rescue_id: r1.id,
    owner_id: o2.id
    ),
p19 = Pet.create(
    name: "Spaz",
    species: "rodent",
    breed: "hamster",
    age: "young",
    gender: "boy",
    size: "small",
    spayed_neutered: "no",
    housetrained: "no", 
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Spaz is the most fun hamster around",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895000/1/?bust=1646688705&width=1080",
   adoptable: "yes",
    url: "https://www.petfinder.com/small-furry/spaz-1-2-off-adoption-fee-54895000/mn/mankato/mending-spirits-animal-rescue-mn379/",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p20 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "girl",
    size: "Small",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no",
    good_with_animals: "yes",
    description: "Sweet kitty named Harper",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895010/1/?bust=1646687223&width=100",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/harper-54895010/nb/fredericton/carma-fredericton-chapter-nb17/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Harper",
    rescue_id: r1.id,
    owner_id: o2.id
    ), 
p21 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "Sweet kitty named Harper",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895009/1/?bust=1646687828&width=1080", 
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/nathasha-54895009/qc/montreal/spca-montreal-qc06/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Nathasha",
    rescue_id: r1.id,
    owner_id: o2.id
    ), 
p22 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "Baby",
    gender: "boy",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "no",
    good_with_animals: "yes",
    description: "Friendly and playful boy kitten",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895002/1/?bust=1646687208&width=100",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/tommy-54895002/il/chicago/red-door-animal-shelter-il89/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Tommy",
    rescue_id: r1.id,
    owner_id: o2.id
    )
p23 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "no",
    good_with_animals: "yes",
    description: "friendly, affectionate, playful and funny",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54894994/1/?bust=1646687194&width=100",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/amber-54894994/in/kokomo/kokomo-humane-society-in336/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Amber",
    rescue_id: r2.id,
    owner_id: o2.id
    )
p24 = Pet.create(
    species: "rodent",
    breed: "guinea pig: Silkie/Sheltie Mix",
    age: "Senior",
    gender: "boy",
    size: "small",
    spayed_neutered: "no",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "low",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Sweet, old-man piggy, Enjoys carrots, celery, and romaine lettuce",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54918053/1/?bust=1646856047&width=1080", 
    adoptable: "yes",
    url: "https://www.petfinder.com/small-furry/gunther-54918053/in/wolcott/nwi-chinchilla-rescue-in555/",
    name: "Gunther",
    rescue_id: r2.id,
    owner_id: o2.id
    )
p25 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "no",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "Mature cat named Rhonda",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54894993/1/?bust=1646687824&width=1080", 
    adoptable: "no",
    url: "https://www.petfinder.com/cat/rhonda-54894993/pa/clarks-summit/humane-society-of-lackawanna-county-dba-griffin-pond-animal-shelter-pa164/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Rhonda",
    rescue_id: r1.id,
    owner_id: o2.id
    )
p26 = Pet.create(
    species: "cat",
    breed: "Domestic Long Hair",
    age: "Young",
    gender: "boy",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "Louise the Cat",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54894995/1/?bust=1646860611&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/louise-54894995/mo/kansas-city/kc-pet-project-mo579/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
    name: "Louise",
    rescue_id: r2.id,
    owner_id: o1.id
    )
p27 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "Senior",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "Affectionate, Couch potato, Friendly, Independent, Quiet, Gentle, Loves kisses",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53912490/1/?bust=1639671836&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/savannah-53912490/md/queenstown/queen-annes-county-animal-services-md81/",
    name: "Savannah",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p28 = Pet.create(
    species: "cat",
    breed: "Tuxedo",
    age: "Young",
    gender: "boy",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no",
    good_with_animals: "yes",
    description: "Friendly, Affectionate, Loyal, Gentle, Playful, Funny, Quiet,",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54811052/1/?bust=1646216997&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/ernie-54811052/pa/philadelphia/whiskers-of-love-cat-rescue-and-sanctuary-pa977/",
    name: "Ernie",
    rescue_id: r1.id,
    owner_id: o1.id
    ),
p29 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "Young",
    gender: "boy",
    size: "medium",
    spayed_neutered: "yes",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "He loves his toys, treats, and naps.",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54263483/1/?bust=1646698763&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/bert2-with-ernie2-54263483/nj/stewartsville/feline-urban-rescue-and-rehab-inc-nj356/",
    name: "Bert",
    rescue_id: r2.id,
    owner_id: o1.id
    ),
p30 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "boy",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Medium",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "Couch potato",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/24758889/5/?bust=1597196320&width=1080",
    adoptable: "no",
    url: "https://www.petfinder.com/cat/dash-24758889/tn/maryville/humane-society-of-east-tn-tn736/",
    name: "Dash",
    rescue_id: r1.id,
    owner_id: o2.id
    ),
p31 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "boy",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "medium",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "I am a chubby cheeked, chunky boy!!! ",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54803142/1/?bust=1646696884&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/pillsbury-doughboy-54803142/nc/sanford/carolina-animal-rescue-and-adoption-nc150/",
    name: "Pillsbury Doughboy",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p32 = Pet.create(
    species: "cat",
    breed: "Siamese",
    age: "adult",
    gender: "boy",
    size: "Large",
    spayed_neutered: "yes",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "Low",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "Timid, intelligent, shy!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54672036/1/?bust=1645572368&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/dash-54672036/wa/bellingham/whatcom-humane-society-wa7/",
    name: "Dash",
    rescue_id: r2.id,
    owner_id: o1.id
    ),
p33 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "Young",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "no",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "medium",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Enjoys true crime documentaries!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/52393212/1/?bust=1646440933&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/orchardgrass-52393212/nc/garner/paw-prints-animal-rescue-inc-nc422/",
    name: "Orchardgrass",
    rescue_id: r1.id,
    owner_id: o2.id
    ),
p34 = Pet.create(
    species: "cat",
    breed: "Tabby & Domestic Short Hair",
    age: "Young",
    gender: "girl",
    size: "medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "Medium",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Loves to take naps in the sun and watch what's going on outside!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54881012/1/?bust=1646588929&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/bonnie-54881012/nc/garner/paw-prints-animal-rescue-inc-nc422/",
    name: "Bonnie",
    rescue_id: r2.id,
    owner_id: o1.id
    ),
p35 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "baby",
    gender: "girl",
    size: "medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "yes",
    good_with_animals: "yes",
    description: "Hypoallergic and hyper cat!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53869384/4/?bust=1639241431&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/brenna-53869384/nc/smithfield/johnston-co-animal-protection-league-nc282/",
    name: "Brenna",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p36 = Pet.create(
    species: "cat",
    breed: "Domestic Long Hair",
    age: "Young",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "medium",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "Athletic kitty that loves to pounce!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/52712549/1/?bust=1634530038&width=1080",
    adoptable: "no",
    url: "https://www.petfinder.com/cat/blossom-52712549/nc/fayetteville/thundering-paws-adoption-center-inc-nc591/",
    name: "Blossom",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p37 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "adult",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "yes",
    housetrained: "yes",
    hypoallergenic: "no",
    activity_level: "medium",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "She was injured in a dog attack resulting in paralysis of her back legs",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/50213633/1/?bust=1609960461&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/birdie-50213633/nc/selma/baileys-human-rescue-incorporated-nc1156/",
    name: "Birdie",
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p38 = Pet.create(
    species: "cat",
    breed: "Domestic Short Hair",
    age: "baby",
    gender: "girl",
    size: "medium",
    spayed_neutered: "no",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "medium",
    good_with_kids: "no",
    good_with_animals: "no",
    description: "Grumpy is still getting used to humans.",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/48824707/1/?bust=1597869862&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/cat/grumpy-48824707/va/hopewell/hopewell-humane-society-inc-va12/",
    name: "Grumpy",
    rescue_id: r1.id,
    owner_id: o1.id
    ),
p39 = Pet.create( 
    species: "rodent",
    breed: "Rat",
    age: "Senior",
    gender: "boy",
    size: "small",
    spayed_neutered: "yes",
    housetrained: "no",
    hypoallergenic: "no",
    activity_level: "High",
    good_with_kids: "no",
    good_with_animals: "yes",
    description: "Loves to snuggle and explore!",
    image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54724309/1/?bust=1646851793&width=1080",
    adoptable: "yes",
    url: "https://www.petfinder.com/small-furry/geoffrey-54724309/nc/raleigh/spca-of-wake-county-nc590/",
    name: "Geoffrey",    
    rescue_id: r2.id,
    owner_id: o2.id
    ),
p40 = Pet.create( 
    species: "turtle",
    breed: "Red eared slider",
    age: "young",
    gender: "girl",
    size: "Medium",
    spayed_neutered: "no",
    housetrained: "no",
    hypoallergenic: "yes",
    activity_level: "low",
    good_with_kids: "yes",
    good_with_animals: "no",
    description: "I'm a big and pretty turtle",
    image: "",
    adoptable: "yes",
    url: "",
    name: "Danko",    
    rescue_id: r2.id,
    owner_id: o2.id
    )
 p41= Pet.create(name: "Nina", 
        species: "dog",
        breed: "Pug Beagle Mix",
        age: "baby",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "no",
        hypoallergenic: "no",
        activity_level: "high",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Friendly, affectionate, Playful, Loves kisses",
        image: “https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54387781/1/?bust=1643213199&width=1080”,
        adoptable: "yes",
        url: " https://www.petfinder.com/dog/nina-54387781/nc/jacksonville/manageable-misfits-nc805/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
    
p42 = Pet.create(name: "Cheesecake", 
        species: "dog",
        breed: "Jack Russell Beagle Mix",
        age: "baby",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "yes",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Cheesecake is a friendly puppy!",
        image: " https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54910183/1/?bust=1646795259&width=1080",
        adoptable: "yes",
        url: " https://www.petfinder.com/dog/cheesecake-54910183/nc/goldsboro/diamonds-in-the-ruff-nc513/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
   p43 =  Pet.create(name: "Duchess", 
        species: "dog",
        breed: "Shar-Pei Mix",
        age: "baby",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "yes",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Friendly, affectionate, loyal, curious, quiet",
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54017809/1/?bust=1640577605&width=1080”
        adoptable: "yes",
        url: " https://www.petfinder.com/dog/dutchess-54017809/nc/vass/mms-fur-ever-furbabies-nc953/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
 p44 = Pet.create(name: "Bonnie", 
        species: "dog",
        breed: "Border Collie",
        age: "adult",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "yes",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Bonnie is a 3 year old",¬¬¬¬
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/54895007/1/?bust=1646687215&width=300",
        adoptable: "yes",
        url: "https://www.petfinder.com/dog/bonnie-54895007/nj/woodbury/good-karma-dog-rescue-nj890/?referrer_id=d5f487d9-4583-4436-9554-7fb9a80b9546",
        rescue_id: r1.id,
        owner_id: o1.id
        )
    p45 = Pet.create(name: "Chloe", 
        species: "dog",
        breed: "Yorkshire Terrier",
        age: "senior",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "yes",
        hypoallergenic: "yes",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Chloe loves HSN, watching ‘The Price is Right’, and playing Bingo with her friends on Thursday nights.",
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53625911/1/?bust=1637376729&width=1080",
        adoptable: "yes",
        url: "https://www.petfinder.com/dog/chloe-in-south-carolina-53625911/sc/florence/yorkshire-terrier-national-rescue-inc-tn321/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
    p46 = Pet.create(name: "Lady Lola", 
        species: "dog",
        breed: "Mixed Breed",
        age: "senior",
        gender: "girl",
        size: "small",
        spayed_neutered: "yes",
        housetrained: "yes",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Quite possibly a Hollywood starlet in a past life, Lola is a great companion and understands several commands.",
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53448872/1/?bust=1646799970&width=1080",
        adoptable: "yes",
        url: "https://www.petfinder.com/dog/lady-lola-53448872/nc/durham/independent-animal-rescue-inc-nc64/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
    p47 = Pet.create(name: "Roxie", 
        species: "Bird",
        breed: "Amazon Parrot",
        age: "senior",
        gender: "girl",
        size: "medium",
        spayed_neutered: "yes",
        housetrained: "no",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "no",
        good_with_animals: "yes",
        description: "Roxie is a 42-year old Parrot who loves long showers and personal space.”
        image: " https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/53889937/1/?bust=1639426365&width=1080",
        adoptable: "yes",
        url:  "https://www.petfinder.com/bird/roxie-53889937/nc/cary/phoenix-landing-foundation-nc676/",
        rescue_id: r1.id,
        owner_id: o1.id
        )
    
    p49 = Pet.create(name: "Maokai", 
        species: "reptile",
        breed: "Water Dragon",
        age: "young",
        gender: "boy",
        size: "small",
        spayed_neutered: "no",
        housetrained: "no",
        hypoallergenic: "yes",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Was abandoned in a grocery store with 3 friends.”
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/51589313/2/?bust=1644983982&width=1080",
        adoptable: "yes",
        url: "https://www.petfinder.com/scales-fins-others/maokai-51589313/nc/durham/bewild-nc1099/
        rescue_id: r1.id,
        owner_id: o1.id) 
    p50 = Pet.create(name: "Mr. Peabody", 
        species: "bird",
        breed: "Peacock",
        age: "adult",
        gender: "male",
        size: "medium",
        spayed_neutered: "no",
        housetrained: "no",
        hypoallergenic: "no",
        activity_level: "null",
        good_with_kids: "yes",
        good_with_animals: "yes",
        description: "Mr. Peabody enjoys strutting his stuff!”
        image: "https://dl5zpyw5k3jeb.cloudfront.net/photos/pets/52489423/2/?bust=1627416160&width=1080",
        adoptable: "yes",
        url: "https://www.petfinder.com/bird/peafowl-52489423/nc/durham/blind-spot-animals-sanctuary-nc1001/
        rescue_id: r1.id,
        owner_id: o1.id
        )
    

puts "🌱Seeding favorites"
f1 = Favorite.create(owner_id: o1.id, pet_id: p1.id)



puts "✅ Done seeding!"
